version: '3.9'

services:
  postgres:    
    image: postgres
    container_name: dev_postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD=postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
volumes:
  postgres:
